/**/callback({
  "meta": {
    "X-RateLimit-Limit": "60",
    "X-RateLimit-Remaining": "59",
    "X-RateLimit-Reset": "1403160235",
    "Cache-Control": "public, max-age=60, s-maxage=60",
    "Last-Modified": "Thu, 19 Jun 2014 03:14:16 GMT",
    "Vary": "Accept",
    "ETag": "\"c1b62d3bd9fc9f936d7ab1910f73a8ff\"",
    "X-GitHub-Media-Type": "github.v3",
    "status": 200
  },
  "data": {
    "login": "hilios",
    "id": 688876,
    "avatar_url": "https://avatars.githubusercontent.com/u/688876?",
    "gravatar_id": "2271bf52979596c61067925326d83091",
    "url": "https://api.github.com/users/hilios",
    "html_url": "https://github.com/hilios",
    "followers_url": "https://api.github.com/users/hilios/followers",
    "following_url": "https://api.github.com/users/hilios/following{/other_user}",
    "gists_url": "https://api.github.com/users/hilios/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/hilios/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/hilios/subscriptions",
    "organizations_url": "https://api.github.com/users/hilios/orgs",
    "repos_url": "https://api.github.com/users/hilios/repos",
    "events_url": "https://api.github.com/users/hilios/events{/privacy}",
    "received_events_url": "https://api.github.com/users/hilios/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Edson Hilios",
    "company": null,
    "blog": "http://edson.hilios.com.br",
    "location": "SP, Brazil",
    "email": null,
    "hireable": true,
    "bio": "Ten years experience with the Net, software development and system analysis, active in the open source community, has the ability to communicate efficiently with managers, designer and others developers, has a great sense o team spirit and leadership. Ability to analyze an issue at the root of its cause and provide solutions for it.\r\n\r\n*  Proficient in English, a little in spanish and native portuguese.\r\n*  Deep knowledge in Ruby, Python, ActionScript 3.0, C++ and PHP.\r\n*  Already worked with server-side frameworks: Rails, Sinatra, Merb, Django and Zend. Client-side: jQuery, PrototypeJS and Flex.\r\n*  Usage of source version controls like GIT and SVN.\r\n*  Updated and used with agile managing styles like XP, Scrum, BDD/TDD e Continuos Integration.\r\n*  Knowledge in front-end technologies HTML5, XHMTL, CSS and Javascript and the main transactional languages XML, JSON and SOAP.\r\n*  Used to Apache, nginx, Passenger, Pow, SSH, Shell, VI and Mac OSX.\r\n*  Experience with VOD and Streaming beginning on encoding to publishing.\r\n*  Acquaintance in business modeling and management, accountability, business intelligence and knowledge management.",
    "public_repos": 22,
    "public_gists": 22,
    "followers": 18,
    "following": 6,
    "created_at": "2011-03-24T18:32:11Z",
    "updated_at": "2014-06-19T03:14:16Z"
  }
})
